revent.py: fixed a bug, where attribute didn't exist. Traceback here:
 File
  "/Users/rcs/Research/UCB/mainline_pox/pox/lib/revent/revent.py", line 155, in
    raiseEvent
    if event.source is None: event.source = self
        AttributeError: 'SwitchJoin' object has no attribute 'source'